version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: library_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./library_api
      dockerfile: Dockerfile
    container_name: library_backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data:
