"""Add cover_image_url to books table

Revision ID: 006c91c7d290
Revises: c1cdc83b5b46
Create Date: 2025-11-20 11:17:12.581515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '006c91c7d290'
down_revision: Union[str, Sequence[str], None] = 'c1cdc83b5b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_image_url')
    # ### end Alembic commands ###
