"""Add email_verified and updated_at to User model

Revision ID: bcc16a7bdfca
Revises: 006c91c7d290
Create Date: 2025-11-20 13:26:51.135632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc16a7bdfca'
down_revision: Union[str, Sequence[str], None] = '006c91c7d290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
